{
  "name": "quiz-sondaggi-app",
  "version": "1.0.0",
  "description": "App per somministrare test a risposta multipla e sondaggi anonimi tramite link",
  "main": "server.js",
  "engines": {
    "node": ">=18.0.0"
  },
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.19.2",
    "pdfkit": "^0.15.0"
  }
}
